---
name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  superlinter:
    runs-on: ubuntu-latest

    # Skip on dependabot PRs
    if: startsWith(github.head_ref, 'dependabot') == false

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Super-Linter
        #uses: docker://github/super-linter:latest
        uses: GaboFDC/super-linter@gf_fix_testcase_change
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          VALIDATE_ALL_CODEBASE: false
          ACTIONS_RUNNER_DEBUG: true
